spring:
  application:
    name: cell-monitoring-system

  datasource:
    url: jdbc:postgresql://localhost:5432/cell_monitoring_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # Измените на create для первого запуска
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20

  sql:
    init:
      mode: never
      data-locations: classpath:data.sql
      # Отключаем проверку существования таблиц
      continue-on-error: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/

logging:
  level:
    org.springframework.jdbc: DEBUG
    org.hibernate.SQL: DEBUG

server:
  port: 8080